Repository code-is-evenly-cooked/even-IDE-front, pull requests merged in 2025-04, with the labels that each got.

#2 베이스 레이아웃 및 헤더 생성
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.tsx
Labels: 🌟 feat

#4 배포용 깃헙액션 설정
  .github/workflows/deploy.yml
  build.sh
Labels: 🌟 feat

#5 tailwind 버전 변경 및 baseInput 생성
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/common/Input/BaseInput.tsx
  src/components/common/Input/TextInput.tsx
  src/components/layout/Header/Header.tsx
  src/types/input.d.ts
  tailwind.config.js
Labels: 🌟 feat

#6 코드 편집기와 터미널과 실행 버튼
  package-lock.json
  package.json
  src/app/editor/page.tsx
  src/components/editor/CodeEditor.tsx
  src/components/editor/RunButton.tsx
  src/components/editor/Terminal.tsx
  src/stores/useCodeStore.ts
Labels: 🌟 feat, 🎨 UI

#7 공용 버튼 컴포넌트 생성
  public/icons/close.svg
  public/icons/eye.svg
  public/icons/google.svg
  public/icons/kakao.svg
  src/app/login/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/common/Button/BaseButton.tsx
  src/components/common/Button/SocialLoginButton.tsx
  src/components/common/Icons/index.tsx
  src/types/button.d.ts
  tailwind.config.js
Labels: 🌟 feat

#8 로그인 UI 생성
  public/icons/even.svg
  public/icons/eye.svg
  public/icons/eyeClose.svg
  src/app/globals.css
  src/app/login/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LoginForm/LoginForm.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/common/Button/BaseButton.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Button/SocialLoginButton.tsx
  src/components/common/Button/styles.ts
  src/components/common/Icons/index.tsx
  src/components/common/Input/BaseInput.tsx
  src/components/common/Input/PasswordInput.tsx
  src/components/common/LoadingSpinner/LoadingSpinner.tsx
  src/types/button.d.ts
Labels: 🌟 feat

#9 코드 편집기 레이아웃 수정, 전용 헤더와 사이드바 추가, 자바스크립트 실행 기능
  src/app/editor/page.tsx
  src/components/editor/CodeEditor.tsx
  src/components/editor/FileExplorer.tsx
  src/components/editor/Terminal.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/stores/useLanguageStore.ts
  tailwind.config.js
Labels: 🌟 feat, 🎨 UI

#10 회원가입 UI 생성
  package-lock.json
  package.json
  src/app/signup/page.tsx
  src/components/auth/LoginForm/LoginForm.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/auth/Signup/SignupForm.tsx
  src/components/auth/Signup/useSignupForm.ts
  src/components/common/Button/Agreement/AgreementItem.tsx
  src/components/common/Button/Agreement/AgreementList.tsx
  src/components/common/Button/styles.ts
  src/components/common/Input/BaseInput.tsx
  src/types/agreement.d.ts
Labels: 🌟 feat

#12 비밀번호 재설정 페이지 추가
  src/app/reset-password/page.tsx
  src/components/auth/LoginForm/LoginForm.tsx
  src/components/auth/ResetPassword/ResetPasswordForm.tsx
  src/components/auth/ResetPassword/useResetPasswordForm.ts
Labels: 🌟 feat

#13 메인화면 랜딩 페이지 추가
  public/icons/evenBig.svg
  src/app/page.tsx
  src/components/common/Icons/index.tsx
  src/components/landing/Landing.tsx
Labels: 🌟 feat

#15 깃헙 액션 배포시간 변경
  .github/workflows/deploy.yml
Labels: 🌟 feat

#16 회원가입/로그인/비밀번호재설정 API 연결
  .env.example
  .gitignore
  src/app/api/auth/login/route.ts
  src/app/api/auth/password-reset/route.ts
  src/app/api/auth/signup/route.ts
  src/app/reset-password/page.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/auth/PasswordReset/PasswordResetForm.tsx
  src/components/auth/PasswordReset/usePasswordResetForm.ts
  src/components/auth/Signup/useSignupForm.ts
  src/lib/api.ts
  src/lib/fetch.ts
  src/lib/response.ts
  src/service/auth.ts
  src/types/auth.d.ts
  src/types/response.d.ts
Labels: 🌟 feat

#14 로그인 유도 팝업창 페이지 구현
  src/app/hyunhatest/page.tsx
  src/components/auth/LoginPopup/LoginPopup.tsx
Labels: 🌟 feat, 🎨 UI

#17 에디터 디자인과 파일 탐색기 기능 구현 및 파일 탭 연동
  .gitignore
  package-lock.json
  package.json
  public/icons/back.svg
  public/icons/close2.svg
  public/icons/file.svg
  public/icons/fileNew.svg
  public/icons/folder.svg
  public/icons/folderNew.svg
  src/app/editor/page.tsx
  src/components/common/Icons/index.tsx
  src/components/editor/CodeEditor.tsx
  src/components/editor/FileExplorer.tsx
  src/components/editor/RunButton.tsx
  src/components/editor/Tabbar.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/stores/useCodeStore.ts
  src/stores/useIdeStore.ts
  tailwind.config.js
Labels: 🌟 feat, ♻️ refactor, 🎨 UI

#18 로그인 상태 전역으로 저장
  package-lock.json
  package.json
  src/app/api/auth/login/route.ts
  src/app/api/auth/password-reset/route.ts
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.tsx
  src/hooks/useAuthInitializer.ts
  src/lib/cookie.ts
  src/service/auth.ts
  src/stores/useAuthStore.ts
  src/types/auth.d.ts
  src/utils/decodeJwt.ts
Labels: 🌟 feat

#20 파일 이름 수정 구현과 단축키 추가, 파일 이름과 탭이 오버플로우 시, 내보내기와 가져오기 버튼 추가 및 내보내기 구현
  package-lock.json
  package.json
  src/app/editor/page.tsx
  src/app/globals.css
  src/components/editor/FileExplorer.tsx
  src/components/editor/HeaderActions.tsx
  src/components/editor/Tabbar.tsx
  src/components/layout/Header/Header.tsx
Labels: 🌟 feat, 🎨 UI

#21 오른쪽 사이드바 영역 추가
  src/app/editor/page.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Button/styles.ts
  src/components/common/Input/BaseInput.tsx
  src/components/common/Input/PasswordInput.tsx
  src/components/editor/CodeEditor.tsx
  src/components/editor/HeaderActions.tsx
  src/components/editor/Tabbar.tsx
  src/components/editor/Terminal.tsx
  src/components/editor/Toolbox/Toolbox.tsx
  src/types/button.d.ts
  src/types/panel.ts
  tailwind.config.js
Labels: 🌟 feat

#26 누락된 파일 추가
  package-lock.json
  package.json
  public/icons/chatTransfer.svg
  public/icons/qna.svg
  public/icons/qrcode.svg
  src/app/api/chat/history/route.ts
  src/app/api/chat/join/route.ts
  src/app/editor/page.tsx
  src/app/layout.tsx
  src/components/auth/AppProviders.tsx
  src/components/editor/HeaderActions.tsx
  src/components/editor/RightPanel/Chat/ChatInput.tsx
  src/components/editor/RightPanel/Chat/ChatMessageList.tsx
  src/components/editor/RightPanel/Chat/ChatModal.tsx
  src/components/editor/RightPanel/Chat/ChatPanel.tsx
  src/components/editor/RightPanel/Chat/ChatTitle.tsx
  src/components/editor/RightPanel/Chat/SendButton.tsx
  src/components/editor/RightPanel/RightPanel.tsx
  src/components/editor/ShareQR.tsx
  src/components/editor/Toolbox/Toolbox.tsx
  src/components/layout/Layout.tsx
  src/hooks/useChat.ts
  src/providers/AppProviders.tsx
  src/providers/ChatProvider.tsx
  src/stores/useChatStore.ts
  src/stores/useIdeStore.ts
  src/types/chat.ts
  src/types/panel.ts
  src/types/sockjs-client.d.ts
  tsconfig.json
Labels: 🌟 feat

#23 비밀번호 재설정 폼 구현
  src/app/update-password/page.tsx
  src/components/auth/PasswordReset/usePasswordResetForm.ts
  src/components/auth/PasswordUpdate/PasswordUpdateForm.tsx
Labels: 🎨 UI

#28 채팅사용자 닉네임 적용
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/chat/history/route.ts
  src/app/api/chat/join/route.ts
  src/app/editor/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/editor/CodeEditor.tsx
  src/components/editor/MemoLine.tsx
  src/components/editor/Toolbox/Toolbox.tsx
  src/lib/chatStorage.ts
  src/lib/useChatIdentity.ts
  src/providers/AppProviders.tsx
  src/providers/ChatProvider.tsx
  src/stores/useAuthStore.ts
  src/stores/useProjectStore.ts
  src/types/auth.d.ts
  src/types/next-auth.d.ts
Labels: 🌟 feat

#29 날짜 아이템추가, 채팅 액션 개선
  package-lock.json
  package.json
  src/app/editor/page.tsx
  src/components/editor/RightPanel/Chat/ChatMessageList.tsx
  src/components/editor/RightPanel/Chat/ChatModal.tsx
  src/components/editor/RightPanel/Chat/ChatPanel.tsx
  src/hooks/useAuthInitializer.ts
  src/providers/ChatProvider.tsx
  src/stores/useChatStore.ts
  src/types/auth.d.ts
  src/types/chat.ts
  src/utils/chat.ts
Labels: 🌟 feat

#31 AI 채팅 영역 추가
  public/icons/icon-ai.svg
  src/components/common/Icons/index.tsx
  src/components/editor/RightPanel/Chat/AI/AIPanel.tsx
  src/components/editor/RightPanel/Chat/ChatModal.tsx
  src/components/editor/RightPanel/Chat/ChatPanel.tsx
  src/components/editor/RightPanel/Chat/ChatTitle.tsx
  src/components/editor/RightPanel/Chat/common/ChatInput.tsx
  src/components/editor/RightPanel/RightPanel.tsx
  src/components/editor/Toolbox/Toolbox.tsx
  src/stores/useChatStore.ts
  src/stores/usePanelState.ts
Labels: 🌟 feat

#32 AI 채팅 추가
  package-lock.json
  package.json
  public/icons/minus_close.svg
  src/app/api/ai/ask/route.ts
  src/components/auth/LoginForm.tsx
  src/components/common/Icons/index.tsx
  src/components/editor/RightPanel/Chat/AI/AIInput.tsx
  src/components/editor/RightPanel/Chat/AI/AIMessageList.tsx
  src/components/editor/RightPanel/Chat/AI/AIPanel.tsx
  src/components/editor/RightPanel/Chat/AI/AITitle.tsx
  src/components/editor/RightPanel/Chat/AI/requestAIResponse.ts
  src/components/editor/RightPanel/Chat/ChatInput.tsx
  src/components/editor/RightPanel/Chat/ChatMessageList.tsx
  src/components/editor/RightPanel/Chat/ChatModal.tsx
  src/components/editor/RightPanel/Chat/ChatPanel.tsx
  src/components/editor/RightPanel/Chat/ChatTitle.tsx
  src/components/editor/RightPanel/Chat/common/MessageInput.tsx
  src/components/editor/RightPanel/Chat/common/SendButton.tsx
  src/components/editor/RightPanel/RightPanel.tsx
  src/components/layout/Header/Header.tsx
  src/hooks/useInitAIChat.ts
  src/lib/fetch.ts
  src/lib/indexedDB.ts
  src/service/ai.ts
  src/stores/useAIChatStore.ts
  src/stores/useChatStore.ts
Labels: 🌟 feat

#36 채팅 연결 실패시 예외처리 추가
  src/components/editor/RightPanel/Chat/ChatInput.tsx
  src/components/editor/RightPanel/Chat/common/MessageInput.tsx
  src/hooks/useChat.ts
  src/providers/AppProviders.tsx
  src/providers/ChatProvider.tsx
Labels: 🐛 bug

#40 코드 잠금 토글 기능
  src/app/api/projects/[projectId]/files/[fileId]/edit/lock/route.ts
  src/app/project/[uuid]/page.tsx
  src/components/common/Icons/index.tsx
  src/components/editor/CodeEditor.tsx
  src/components/editor/EditLockToggle.tsx
  src/service/file.ts
  src/stores/useIdeStore.ts
Labels: 🌟 feat, 🎨 UI

#42 파일 잠금 호출 빌드 실패 오류 수정
  src/app/api/projects/[projectId]/files/[fileId]/edit/lock/route.ts
Labels: 🐛 bug

#41 파일 조회, 저장, 삭제 안정화와 탐색기 개별 선택, 코드 실행 기능 추가
  public/icons/menu.svg
  src/app/editor/page.tsx
  src/app/project/[uuid]/page.tsx
  src/components/common/Icons/index.tsx
  src/components/editor/CodeEditor.tsx
  src/components/editor/FileExplorer.tsx
  src/components/editor/HeaderActions.tsx
  src/components/editor/RunButton.tsx
  src/components/editor/Tabbar.tsx
  src/components/editor/Terminal.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/service/code.ts
  src/service/file.ts
  src/service/project.ts
  src/stores/useIdeStore.ts
  src/stores/useLanguageStore.ts
  src/types/file.ts
Labels: 🐛 bug, 🌟 feat

#43 파일 생성과 파일 이름 변경 버그 및 편의성 개선
  src/app/globals.css
  src/app/project/[uuid]/page.tsx
  src/components/editor/FileExplorer.tsx
  src/components/editor/LanguageDropdown.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/service/file.ts
  src/stores/useIdeStore.ts
Labels: 🐛 bug, 🌟 feat

#44 이용약관 및 개인정보처리방침 모달, 파비콘 추가
  package-lock.json
  package.json
  public/favicon.svg
  public/terms/privacy-policy.md
  public/terms/terms-of-service.md
  src/app/layout.tsx
  src/components/common/Button/Agreement/AgreementItem.tsx
  src/components/common/Button/Agreement/AgreementList.tsx
  src/components/modal/TermsModal.tsx
  tailwind.config.cjs
Labels: 🌟 feat, 🎨 UI

#50 스크롤바 디자인 변경
  src/app/api/auth/refresh/route.ts
  src/app/api/chat/join/route.ts
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/editor/RightPanel/Chat/ChatModal.tsx
  src/components/editor/RightPanel/Chat/ChatPanel.tsx
  src/lib/cookie.ts
  src/lib/fetch.ts
Labels: 🌟 feat

#48 실시간 코드 편집 웹소켓 연결
  src/components/editor/CodeEditor.tsx
  src/providers/ChatProvider.tsx
Labels: 🌟 feat

#51 코드 실행 버튼 색상 변경과 토스트 팝업과 로그인 유도 팝업 추가
  src/app/layout.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/components/editor/RightPanel/Chat/ChatTitle.tsx
  src/components/editor/RunButton.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/stores/useToastStore.ts
Labels: 🌟 feat, 🎨 UI

#52 getAuthcookie 호출 방식 변경
  src/app/api/auth/forgot-password/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/auth/password-reset/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/chat/history/route.ts
  src/app/editor/page.tsx
  src/app/project/[uuid]/page.tsx
  src/components/editor/CodeEditor.tsx
  src/components/editor/FileExplorer.tsx
  src/components/editor/HeaderActions.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/hooks/useAuthInitializer.ts
  src/lib/useChatIdentity.ts
  src/providers/ChatProvider.tsx
  src/service/ai.ts
  src/service/auth.ts
  src/service/file.ts
Labels: 🌟 feat

#53 프로젝트 페이지 별도 파비콘과 타이틀 적용
  src/app/project/[uuid]/layout.tsx
Labels: 🐛 bug

#54 access token 만료 조건 추가 및 스크롤바 css 수정
  src/app/globals.css
  src/components/layout/Header/Header.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/lib/token.ts
Labels: 🌟 feat

#57 Create README.md
  README.md
Labels: 📝 docs
